import bcrypt from "bcryptjs";
const data = {
  users: [
    {
      name: "harsha",
      email: "renukuntaharsharaj@gmail.com",
      password: bcrypt.hashSync("1234", 8),
      isAdmin: true,
    },
    {
      name: "Kalyan",
      email: "KalyanMSD@gmail.com",
      password: bcrypt.hashSync("1234", 8),
      isAdmin: false,
    },
  ],
  product: [
    {
      name: "nike slim shirt",
      category: "shirts",
      image: "/images/p1.jpg",
      price: 780,
      countInStock: 120,
      brand: "nike",
      rating: 4.5,
      numReview: 10,
      description: "high quality T-Shirts from Nike",
    },
    {
      name: "adidas shirt",
      category: "shirts",
      image: "/images/p2.jpg",
      price: 790,
      countInStock: 120,
      brand: "adidas",
      rating: 4.0,
      numReview: 20,
      description: "high quality T-Shirts from adidas",
    },
    {
      name: "nike shirt1",
      category: "shirts",
      image: "/images/p3.jpg",
      price: 900,
      countInStock: 0,
      brand: "nike",
      rating: 4.5,
      numReview: 15,
      description: "high quality T-Shirts from Nike",
    },
    {
      name: "nike pant",
      category: "pants",
      image: "/images/p4.jpg",
      price: 1200,
      countInStock: 120,
      brand: "nike",
      rating: 3.5,
      numReview: 12,
      description: "high quality pants from Nike",
    },
    {
      name: "adidas pants",
      category: "pants",
      image: "/images/p5.jpg",
      price: 780,
      countInStock: 120,
      brand: "addidas",
      rating: 4.5,
      numReview: 10,
      description: "high quality pants from Adidas",
    },
    {
      name: "rebok pant",
      category: "pants",
      image: "/images/p6.jpg",
      price: 1100,
      countInStock: 120,
      brand: "rebok",
      rating: 4.5,
      numReview: 10,
      description: "high quality pants from Rebook",
    },
  ],
};

export default data;
